# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjt87HxTltnmWKzRQtgEROu_eWOA3y-t
"""

print ("Hello world")